MapReduce/Controllers/ConfigController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BusinessLogic;

namespace MapReduce.Controllers
{
    public class ConfigController : Controller
    {
        private readonly HandleIpAddresses handleIpAddresses;

        public ConfigController()
        {
            this.handleIpAddresses = new HandleIpAddresses();
        }

        public ActionResult Index()
        {
            IEnumerable<string> ipAddresses = handleIpAddresses.GetSavedIpAddressesFromTxtFile().OrderBy(x => x);
            return View(ipAddresses);
        }

        [HttpPost]
        public JsonResult SaveIpAddresses(string ipAddresses)
        {
            if (ModelState.IsValid)
            {
                bool result = handleIpAddresses.StoreIpAddresses(ipAddresses);

                IEnumerable<string> newIpAddressesSequence = handleIpAddresses.GetSavedIpAddressesFromTxtFile().OrderBy(x => x);

                object[] finalResult = new object[] { result, newIpAddressesSequence };
                return Json(finalResult);
            }
            return Json(false);
        }
	}
}

MapReduce/Controllers/NonMapReduceController.cs
using BusinessLogic;
using Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MapReduce.Controllers
{
    public class NonMapReduceController : Controller
    {
        private readonly Dummy dummy;
        private readonly WithoutMapAndReduce withoutMapAndReduce;
        private readonly WithoutMapAndReduce2 withoutMapAndReduce2;
        private readonly WithoutMapAndReduce3 withoutMapAndReduce3;

        private static IEnumerable<SchoolClass> schoolClasses;

        public NonMapReduceController()
        {
            this.dummy = new Dummy();
            this.withoutMapAndReduce = new WithoutMapAndReduce();
            this.withoutMapAndReduce2 = new WithoutMapAndReduce2();
            this.withoutMapAndReduce3 = new WithoutMapAndReduce3();
        }

        public ActionResult Index()
        {
            int amountOfDummyValues = 500;

            schoolClasses = dummy.GenerateDummyValues(amountOfDummyValues);

            return View(schoolClasses);
        }

        [HttpPost]
        public JsonResult FemaleStudentsCount()
        {
            Stopwatch watch = Stopwatch.StartNew();

            //locally way
            int result = withoutMapAndReduce.TriggerMapAndReduce();

            //get elapsed time
            watch.Stop();
            object[] finalResult = new object[] { result, watch.Elapsed.TotalSeconds };
            return Json(finalResult);
        }

        [HttpPost]
        public JsonResult SearchAfterLastname(string searchName)
        {
            Stopwatch watch = Stopwatch.StartNew();

            if (searchName.Trim().Length > 0)
            {
                //locally way
                int result = withoutMapAndReduce2.TriggerMapAndReduce(searchName.Trim());

                //get elapsed time
                watch.Stop();
                object[] finalResult = new object[] { result, watch.Elapsed.TotalSeconds };
                return Json(finalResult);
            }

            return new JsonResult();
        }

        [HttpPost]
        public JsonResult MinorStudents()
        {
            Stopwatch watch = Stopwatch.StartNew();

            //locally way
            int result = withoutMapAndReduce3.TriggerMapAndReduce();

            //get elapsed time
            watch.Stop();
            object[] finalResult = new object[] { result, watch.Elapsed.TotalSeconds };
            return Json(finalResult);
        }
    }
}

MapReduce/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>@ViewBag.Title - Steinam</title>
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("MapReduce Beispielanwendung - Server", "Index", "Home", null, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Übersicht mit MapReduce", "Index", "Home")</li>
                        <li>@Html.ActionLink("Übersicht ohne MapReduce", "Index", "NonMapReduce")</li>
                        <li>@Html.ActionLink("Konfiguration", "Index", "Config")</li>
                    </ul>
                    @*@Html.Partial("_LoginPartial")*@
                </div>
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                @if (DateTime.Now.Year == 2016)
                {
                    <p>&copy; @DateTime.Now.Year Freudinger, Golunski & Brenner (11FI1 - Schuljahr 2015/2016)</p>
                }
                else
                {
                    <p>&copy; 2016 - @DateTime.Now.Year Freudinger, Golunski & Brenner (11FI1 - Schuljahr 2015/2016)</p>
                }
            </footer>
        </div>

        @RenderSection("scripts", required: false)
    </body>
</html>